AFFINE-GAP-PENALTY-ALIGNMENT = $(shell pwd)

all:
	@make -C src AFFINE-GAP-PENALTY-ALIGNMENT=$(AFFINE-GAP-PENALTY-ALIGNMENT) OPT=1

install:
	@make -C src AFFINE-GAP-PENALTY-ALIGNMENT=$(AFFINE-GAP-PENALTY-ALIGNMENT) OPT=1 install

test:
	@make -C src AFFINE-GAP-PENALTY-ALIGNMENT=$(AFFINE-GAP-PENALTY-ALIGNMENT) test
.PHONY: test

clean:
	@make -C src AFFINE-GAP-PENALTY-ALIGNMENT=$(AFFINE-GAP-PENALTY-ALIGNMENT) clean
.PHONY: clean

distclean: clean
	@rm -rf $(AFFINE-GAP-PENALTY-ALIGNMENT)/bin
	@rm -rf $(AFFINE-GAP-PENALTY-ALIGNMENT)/include
.PHONY: distclean
